panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: http://hassio.local:3218

light:
  - platform: decora_wifi
    username: !secret decora_username
    password: !secret decora_password