panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: http://hassio.local:3218

light:
  - platform: decora_wifi
    scan_interval: 2
    username: !secret decora_username
    password: !secret decora_password

group:
  kitchen:
    - light.kitchen__island
    - light.kitchen__sink

automation:
  - id: kitchen_lights_on
    alias: Turn on all kitchen lights when one is turned on
    trigger:
      - platform: state
        entity_id:
          - light.kitchen__island
          - light.kitchen__sink
        from: 'off'
        to: 'on'
    action:
      - service: light.turn_on
        data:
          entity_id: group.kitchen

  - id: kitchen_lights_off
    alias: Turn off all kitchen lights when one is turned off
    trigger:
      - platform: state
        entity_id:
          - light.kitchen__island
          - light.kitchen__sink
        from: 'on'
        to: 'off'
    action:
      - service: light.turn_off
        data:
          entity_id: group.kitchen