homeassistant:
  name: "Caleb"
  latitude: 0
  longitude: 0
  elevation: 0
  unit_system: metric
  time_zone: United States/Seattle

tts:
  - platform: google

logbook:
exclude:
  entities:
    - sensor.time
    - sensor.date
  domains:
    - sun

logger:
  default: warn
map:
ios:
config: